
  name: update-wakatime-stats

  on:
    schedule:
      - cron: '0 0 * * *'
    workflow_dispatch:

  jobs:
    update-wakatime-stats:
      name: Update Readme with Wakatime Stats
      runs-on: ubuntu-latest
      steps:
        - uses: anmol098/waka-readme-stats@master  # https://github.com/anmol098/waka-readme-stats
          with:
            WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
            COMMIT_MESSAGE: 'refactor[wakatime]: update wakatime stats'
            SHOW_UPDATED_DATE: "True"
            SHOW_PROFILE_VIEWS: "False"
            SHOW_LOC_CHART: "False"
            SHOW_LINES_OF_CODE: "True"
            SHOW_SHORT_INFO: "False"
